# Generated by Django 4.1.2 on 2022-10-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ("name",)},
        ),
    ]
